stages:
  preprocess:
    cmd: python codes/preprocessing.py
    deps:
    - codes/preprocessing.py
    - datasets/shoe_sales_clean.csv
    outs:
    - datasets/preprocessed_data.csv
  train:
    cmd: python codes/train.py
    deps:
    - codes/train.py
    - datasets/preprocessed_data.csv
    outs:
    - metrics.txt
